name: parser

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run parser
        run: |
          python parser.py

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add output.txt
          git diff --cached --quiet && echo "No changes" || git commit -m "update configs"

      - name: Push changes
        run: |
          git push origin HEAD
